---
- hosts: all

  tasks:
    - include_role:
        name: 2do_parcial
    
    - name: "Otra tarea"
      debug:
        msg: "Despues de la ejecucion del rol"

    - name: "Import nuevo_role"
      import_role:
        name: nuevo_role
      tags:
        - nuevo_role
